# Use official devcontainers Java image as the base
FROM mcr.microsoft.com/devcontainers/java:21

# Install Docker CLI
RUN apt-get update && apt-get install -y docker.io

# Set working directory
WORKDIR /workspace
